version: '3.8'

services:
  db:
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    image: postgres:15.4-bullseye
    restart: always

  # user-segmentation:
  #   build: ./
  #   depends_on: 
  #     - db