version: '3.8'

services:
  db:
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    image: postgres:15.4-bullseye
    restart: always

  user-segmentation:
    container_name: user-segmentation-api
    build: ./cmd/user-segmentation
    command: ./user-segmentation
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DBNAME=postgres
      - POSTGRES_PORT=5432