version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.4-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    volumes:
      - ./database/postgres/.data:/var/lib/postgresql/data
      - ./database/postgres/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3

  user-segmentation:
    container_name: user-segmentation
    build: ./
    command: ./user-segmentation
    ports:
      - 8080:8080
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DBNAME=postgres
      - POSTGRES_PORT=5432