openapi: 3.0.0
info:
  title: "Dynamic user segmentation"
  version: "0.0.1"
servers:
- url: http://localhost:8080/api/v1
  description: "Dev server"
paths:
  /segments/{segment_slug}:
    post:
      description: "Create a new user segment"
      tags:
        - Segments
      operationId: createSegment
      parameters:
        - name: segment_slug
          in: path
          required: true
          description: "Unique segment name"
          schema:
            type: string
          example: "AVITO_VOICE_MESSAGES"
      responses:
        '200':
          description: "Segment created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Segment'
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: "Delete an existing user segment"
      tags:
        - Segments
      operationId: deleteSegment
      parameters:
        - name: segment_slug
          in: path
          required: true
          description: "Unique segment name"
          schema:
            type: string
          example: "AVITO_VOICE_MESSAGES"
      responses:
        '200':
          description: "Segment deleted"
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
  /segments/users/{user_id}:
    get:
      description: "Get active user's segments"
      tags:
        - User's segments
      operationId: getActiveUserSegments
      parameters: 
        - name: user_id
          in: path
          required: true
          description: "User's ID"
          schema: 
            type: integer
      responses:
        '200':
          description: "List of active segments of selected user"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Segment'
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: "Update list of user's segments"
      tags:
        - User's segments
      operationId: updateActiveUserSegments
      parameters: 
        - name: user_id
          in: path
          required: true
          description: "User's ID"
          schema: 
            type: integer
      requestBody:
        description: "Contains segment slugs to include and exclude user from"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                include:
                  type: array
                  items: 
                    type: string
                  example: ["AVITO_VOICE_MESSAGES"]
                exclude:
                  type: array
                  items: 
                    type: string
                  example: ["AVITO_DISCOUNT_30"]
              
      responses:
        '200':
          description: "List of active segments of selected user"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Segment'
        '400':
          description: "Selected user don't participate in one of `exclude` segments or one of `include` segments don't exists or user already participate in one of `include` segments"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    
components:
  schemas:
    Segment:
      type: object
      required: 
        - name
      properties:
        id:
          type: integer
          example: 24
        name:
          type: string
          example: "AVITO_VOICE_MESSAGES"
    Error:
      type: object
      required:
        - code
        - description
      properties:
        code: 
          type: integer
          example: "404"
        description:
          type: string
          example: "Page not found"
